name: Generate Snake

on:
  schedule:
    # 05:00 UTC = 00:00 Bogotá (America/Bogota)
    - cron: "0 5 * * *"
  workflow_dispatch: {}  # para correrlo manualmente

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate SVGs (light & dark)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: AngelQuintero27
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
